// SPDX-License-Identifier: MIT
pragma solidity 0.8.15;

// Libraries
import { SafeCall } from "src/libraries/SafeCall.sol";
import { Predeploys } from "src/libraries/Predeploys.sol";

// Interfaces
import { IL2ToL1MessagePasser } from "interfaces/L2/IL2ToL1MessagePasser.sol";

// Libraries
import { Types } from "src/libraries/Types.sol";

// Base contracts
import { ProxyAdminOwnedBase } from "src/L1/ProxyAdminOwnedBase.sol";
import { Initializable } from "@openzeppelin/contracts/proxy/utils/Initializable.sol";

/// @title FeeVault
/// @notice The FeeVault contract contains the basic logic for the various different vault contracts
///         used to hold fee revenue generated by the L2 system.
abstract contract FeeVault is ProxyAdminOwnedBase, Initializable {
    /// @notice The minimum gas limit for the FeeVault withdrawal transaction.
    uint32 internal constant WITHDRAWAL_MIN_GAS = 400_000;

    /// @notice Total amount of wei processed by the contract.
    uint256 public totalProcessed;

    /// @notice Minimum balance before a withdrawal can be triggered.
    uint256 public minWithdrawalAmount;

    /// @notice Account that will receive the fees. Can be located on L1 or L2.
    address public recipient;

    /// @notice Network which the recipient will receive fees on.
    Types.WithdrawalNetwork public withdrawalNetwork;

    /// @notice Reserve extra slots in the storage layout for future upgrades, 50 in total.
    uint256[46] private __gap;

    /// @notice Emitted each time a withdrawal occurs. This event will be deprecated
    ///         in favor of the Withdrawal event containing the WithdrawalNetwork parameter.
    /// @param value Amount that was withdrawn (in wei).
    /// @param to    Address that the funds were sent to.
    /// @param from  Address that triggered the withdrawal.
    event Withdrawal(uint256 value, address to, address from);

    /// @notice Emitted each time a withdrawal occurs.
    /// @param value             Amount that was withdrawn (in wei).
    /// @param to                Address that the funds were sent to.
    /// @param from              Address that triggered the withdrawal.
    /// @param withdrawalNetwork Network which the to address will receive funds on.
    event Withdrawal(uint256 value, address to, address from, Types.WithdrawalNetwork withdrawalNetwork);

    /// @notice Emitted when the minimum withdrawal amount for the vault is updated.
    /// @param oldWithdrawalAmount The previous minimum withdrawal amount.
    /// @param newWithdrawalAmount The new minimum withdrawal amount.
    event MinWithdrawalAmountUpdated(uint256 oldWithdrawalAmount, uint256 newWithdrawalAmount);

    /// @notice Emitted when the fee recipient for this vault is updated.
    /// @param oldRecipient The previous recipient address.
    /// @param newRecipient The new recipient address.
    event RecipientUpdated(address oldRecipient, address newRecipient);

    /// @notice Emitted when the withdrawal network for this vault is updated.
    /// @param oldWithdrawalNetwork The previous withdrawal network.
    /// @param newWithdrawalNetwork The new withdrawal network.
    event WithdrawalNetworkUpdated(
        Types.WithdrawalNetwork oldWithdrawalNetwork, Types.WithdrawalNetwork newWithdrawalNetwork
    );

    constructor() {
        _disableInitializers();
    }

    /// @notice Initializes the FeeVault with the current configuration.
    /// @param _newRecipient           Wallet that will receive the fees.
    /// @param _newMinWithdrawalAmount Minimum balance for withdrawals.
    /// @param _newWithdrawalNetwork   Network which the recipient will receive fees on.
    function __FeeVault_init(
        address _newRecipient,
        uint256 _newMinWithdrawalAmount,
        Types.WithdrawalNetwork _newWithdrawalNetwork
    )
        public
        onlyInitializing
    {
        _assertOnlyProxyAdminOwner();

        recipient = _newRecipient;
        minWithdrawalAmount = _newMinWithdrawalAmount;
        withdrawalNetwork = _newWithdrawalNetwork;
    }

    /// @notice Allow the contract to receive ETH.
    receive() external payable { }

    /// @notice Updates the minimum amount of funds the SequencerFeeVault contract must hold before they can be
    /// withdrawn.
    /// @param _newMinWithdrawalAmount The new minimum withdrawal amount.
    function setMinWithdrawalAmount(uint256 _newMinWithdrawalAmount) external {
        _assertOnlyProxyAdminOwner();

        uint256 oldWithdrawalAmount = minWithdrawalAmount;
        minWithdrawalAmount = _newMinWithdrawalAmount;

        emit MinWithdrawalAmountUpdated(oldWithdrawalAmount, _newMinWithdrawalAmount);
    }

    /// @notice Updates the recipient of sequencer fees when they are withdrawn from the vault.
    /// @param _newRecipient The new recipient address.
    function setRecipient(address _newRecipient) external {
        _assertOnlyProxyAdminOwner();

        address oldRecipient = recipient;
        recipient = _newRecipient;

        emit RecipientUpdated(oldRecipient, _newRecipient);
    }

    /// @notice Updates the network to which sequencer fees will be withdrawn. This can be either WithdrawalNetwork.L1
    /// to withdraw them to an address on L1 by using the L2ToL1MessagePasser predeploy, or WithdrawalNetwork.L2 to
    /// withdraw them to an address on the same chain.
    /// @param _newWithdrawalNetwork The new withdrawal network.
    function setWithdrawalNetwork(Types.WithdrawalNetwork _newWithdrawalNetwork) external {
        _assertOnlyProxyAdminOwner();

        Types.WithdrawalNetwork oldWithdrawalNetwork = withdrawalNetwork;
        withdrawalNetwork = _newWithdrawalNetwork;

        emit WithdrawalNetworkUpdated(oldWithdrawalNetwork, _newWithdrawalNetwork);
    }

    /// @notice Triggers a withdrawal of funds to the fee wallet on L1 or L2.
    function withdraw() external {
        require(
            address(this).balance >= minWithdrawalAmount,
            "FeeVault: withdrawal amount must be greater than minimum withdrawal amount"
        );

        uint256 value = address(this).balance;
        totalProcessed += value;

        emit Withdrawal(value, recipient, msg.sender);
        emit Withdrawal(value, recipient, msg.sender, withdrawalNetwork);

        if (withdrawalNetwork == Types.WithdrawalNetwork.L2) {
            bool success = SafeCall.send(recipient, value);
            require(success, "FeeVault: failed to send ETH to L2 fee recipient");
        } else {
            IL2ToL1MessagePasser(payable(Predeploys.L2_TO_L1_MESSAGE_PASSER)).initiateWithdrawal{ value: value }({
                _target: recipient,
                _gasLimit: WITHDRAWAL_MIN_GAS,
                _data: hex""
            });
        }
    }
}
