import '../justfiles/go.just'

_LDFLAGSSTRING := "'" + trim(
    "-X main.Version=" + VERSION + " " + \
    "-X main.VersionMeta=" + VERSION_META + " " + \
    "-X main.GitCommit=" + GITCOMMIT + " " + \
    "-X main.GitDate=" + GITDATE + " " + \
    "") + "'"

BINARY := "./bin/op-playground"

default: op-playground

op-playground: (go_build BINARY "." "-ldflags" _LDFLAGSSTRING)

clean:
    rm -f {{ BINARY }}
